In [3]:
import numpy
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [8]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [12]:
m = [[123,12,1,243,5],[],[]]

In [16]:
print(m)
n = numpy.asarray(m)
n

[[123, 12, 1, 243, 5], [], []]


array([list([123, 12, 1, 243, 5]), list([]), list([])], dtype=object)

In [30]:
type(n)

import cv2
import os
os.listdir()
image = cv2.imread("smallgray.png",1)
image


array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [50]:
cv2.imwrite("newsmallgray.png",image)
image2 = cv2.imread("newsmallgray.png",0)
image2
image2[1:3,]

array([[198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [56]:
image2[1,0]


198

In [61]:
ims = numpy.hstack((image2,image2))
imv = numpy.vstack((image2,image2))
imv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)